package com.boa.hackathon.autodocgen.service;

import com.boa.hackathon.autodocgen.model.ClassMetadata;
import com.boa.hackathon.autodocgen.model.MethodMeta;
import com.boa.hackathon.autodocgen.model.ProjectMetadata;
import com.boa.hackathon.autodocgen.util.JsonUtil;
import com.fasterxml.jackson.databind.ObjectMapper;
import net.sourceforge.plantuml.SourceStringReader;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
public class DocGeneratorService {

    public File generateDocsZip(ProjectMetadata pm) throws IOException {
        Path outDir = Files.createTempDirectory("autodoc_output_");

        Path readme = outDir.resolve("README.md");
        String readmeText = buildReadme(pm);
        Files.writeString(readme, readmeText);

        // UML generation
        Path puml = outDir.resolve("diagram.puml");
        String pumlText = buildPlantUml(pm);
        Files.writeString(puml, pumlText);

        Path umlPng = outDir.resolve("diagram.png");
        generateUmlPng(pumlText, umlPng);

        Path meta = outDir.resolve("metadata.json");
        Files.writeString(meta, JsonUtil.toJson(pm));

        Map<String,Object> qualityReport = new LinkedHashMap<>();
        Map<String,Object> analysis = DocQualityAnalyzer.analyzeDocText(readmeText);
        qualityReport.put("docAnalysis", analysis);
        qualityReport.put("similarMethods", DocQualityAnalyzer.detectSimilarMethods(pm.getClasses()));
        qualityReport.put("duplicateMethodBodies", DocQualityAnalyzer.detectDuplicateMethodBodies(pm.getClasses()));

        Path swagger = outDir.resolve("openapi.json");
        Files.writeString(swagger, buildSwagger(pm));

        Path quality = outDir.resolve("quality_report.json");
        ObjectMapper mapper = new ObjectMapper();
        Files.writeString(quality, mapper.writerWithDefaultPrettyPrinter().writeValueAsString(qualityReport));

        Path zip = outDir.resolveSibling(pm.getProjectName() + "_autodoc.zip");
        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(zip))) {
            for (Path p : List.of(readme, puml, umlPng, meta, swagger, quality)) {
                zos.putNextEntry(new ZipEntry(p.getFileName().toString()));
                Files.copy(p, zos);
                zos.closeEntry();
            }
        }
        return zip.toFile();
    }

    private String buildReadme(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(pm.getProjectName()).append("\n\n");
        sb.append("## Auto-generated Overview\n\n");
        sb.append("This documentation was automatically generated by AutoDoc.\n\n");

        for (ClassMetadata c : pm.getClasses()) {
            sb.append("### ").append(c.getClassName()).append(" (").append(c.getType()).append(")\n\n");
            sb.append(c.getAiDescription() != null ? c.getAiDescription() : c.getComment()).append("\n\n");
            if (c.getMethods() != null && !c.getMethods().isEmpty()) {
                sb.append("**Methods**:\n");
                for (MethodMeta m : c.getMethods()) {
                    sb.append("- `").append(m.getName()).append("(");
                    if (m.getParams() != null) sb.append(String.join(", ", m.getParams()));
                    sb.append(")` : ").append(m.getAiDescription() != null ? m.getAiDescription() : m.getComment());
                    sb.append("\n");
                }
                sb.append("\n");
            }
        }
        sb.append("## UML Diagram\n\n");
        sb.append("UML Diagram image is available as `diagram.png`.\n");
        return sb.toString();
    }

    private String buildPlantUml(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("skinparam classAttributeIconSize 0\n");

        for (ClassMetadata c : pm.getClasses()) {
            sb.append("class ").append(ensureId(c.getClassName())).append(" {\n");
            if (c.getFields() != null) {
                for (String f : c.getFields()) sb.append("  ").append(f.replaceAll("[\\[\\]]", "")).append("\n");
            }
            sb.append("}\n");
        }

        for (ClassMetadata c : pm.getClasses()) {
            if (c.getMethods() != null) {
                for (MethodMeta m : c.getMethods()) {
                    if (m.getRepositoryCalls() != null) {
                        for (String rc : m.getRepositoryCalls()) {
                            pm.getClasses().stream()
                                    .filter(x -> x.getClassName().toLowerCase().contains(rc.toLowerCase()) ||
                                            x.getClassName().toLowerCase().contains("repository"))
                                    .findFirst()
                                    .ifPresent(target ->
                                            sb.append(ensureId(c.getClassName())).append(" --> ")
                                                    .append(ensureId(target.getClassName())).append("\n"));
                        }
                    }
                }
            }
        }
        sb.append("@enduml\n");
        return sb.toString();
    }

    private void generateUmlPng(String pumlText, Path outputPng) throws IOException {
        try (FileOutputStream fos = new FileOutputStream(outputPng.toFile())) {
            SourceStringReader reader = new SourceStringReader(pumlText);
            reader.outputImage(fos);
        }
    }

    private String buildSwagger(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n  \"openapi\": \"3.0.3\",\n  \"info\": {\n")
                .append("    \"title\": \"").append(pm.getProjectName()).append("\",\n")
                .append("    \"version\": \"1.0.0\",\n")
                .append("    \"description\": \"Auto-generated API documentation\"\n")
                .append("  },\n  \"components\": {\n")
                .append("    \"securitySchemes\": {\n")
                .append("      \"bearerAuth\": {\n")
                .append("        \"type\": \"http\",\n")
                .append("        \"scheme\": \"bearer\",\n")
                .append("        \"bearerFormat\": \"JWT\"\n")
                .append("      }\n    }\n  },\n")
                .append("  \"security\": [ { \"bearerAuth\": [] } ],\n")
                .append("  \"paths\": {\n");

        for (ClassMetadata c : pm.getClasses()) {
            if (!"Controller".equalsIgnoreCase(c.getType())) continue;
            if (c.getMethods() == null) continue;

            for (MethodMeta m : c.getMethods()) {
                String methodName = m.getName().toLowerCase();


                String verb = "get";
                if (methodName.startsWith("get") || methodName.startsWith("fetch")) verb = "get";
                else if (methodName.startsWith("create") || methodName.startsWith("add") || methodName.startsWith("save")) verb = "post";
                else if (methodName.startsWith("update") || methodName.startsWith("edit") || methodName.startsWith("put")) verb = "put";
                else if (methodName.startsWith("delete") || methodName.startsWith("remove")) verb = "delete";
                else if (methodName.startsWith("patch")) verb = "patch";


                String basePath = "/" + c.getClassName().replace("Controller", "").toLowerCase();
                String path = basePath + "/" + methodName;

                // If method name has "By" (like getProductById), include a path param
                if (methodName.contains("by")) {
                    String[] parts = methodName.split("by");
                    String param = parts.length > 1 ? parts[1].replaceAll("[^a-zA-Z]", "").toLowerCase() : "id";
                    path = basePath + "/{" + param + "}";
                }

                String description = escapeJson(
                        m.getAiDescription() != null ? m.getAiDescription() : m.getComment()
                );

                sb.append("    \"").append(path).append("\": {\n")
                        .append("      \"").append(verb).append("\": {\n")
                        .append("        \"summary\": \"").append(description).append("\",\n")
                        .append("        \"requestBody\": {\n");


                if (!verb.equals("get") && !verb.equals("delete")) {
                    sb.append("          \"content\": {\n")
                            .append("            \"application/json\": {\n")
                            .append("              \"schema\": { \"type\": \"object\" },\n")
                            .append("              \"example\": {\n");

                    if (m.getParams() != null && !m.getParams().isEmpty()) {
                        for (String param : m.getParams()) {
                            String[] parts = param.split(" ");
                            if (parts.length == 2) {
                                sb.append("                \"").append(parts[1]).append("\": \"").append(parts[0]).append("\",\n");
                            }
                        }
                        sb.setLength(sb.length() - 2); // remove last comma
                    } else {
                        sb.append("                \"sampleField\": \"value\"");
                    }
                    sb.append("\n              }\n            }\n          }\n        },\n");
                } else {
                    sb.append("          \"required\": false\n        },\n");
                }


                sb.append("        \"responses\": {\n")
                        .append("          \"200\": {\n")
                        .append("            \"description\": \"Successful response\",\n")
                        .append("            \"content\": {\n")
                        .append("              \"application/json\": {\n")
                        .append("                \"example\": ");

                if (verb.equals("get")) {
                    sb.append("{ \"data\": [{ \"id\": 1, \"name\": \"sample\" }] }");
                } else if (verb.equals("post")) {
                    sb.append("{ \"message\": \"Resource created successfully\", \"id\": 123 }");
                } else if (verb.equals("put") || verb.equals("patch")) {
                    sb.append("{ \"message\": \"Resource updated successfully\" }");
                } else if (verb.equals("delete")) {
                    sb.append("{ \"message\": \"Resource deleted successfully\" }");
                } else {
                    sb.append("{ \"status\": \"ok\" }");
                }

                sb.append("\n              }\n            }\n")
                        .append("          }\n        }\n")
                        .append("      }\n    },\n");
            }
        }

        if (sb.toString().endsWith(",\n")) {
            int last = sb.lastIndexOf(",\n");
            sb.delete(last, last + 2);
        }

        sb.append("  }\n}");
        return sb.toString();
    }


    private String escapeJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", " ");
    }

    private String ensureId(String s) {
        return s.replaceAll("[^A-Za-z0-9_]", "_");
    }
}
