package com.boa.hackathon.autodocgen.service;


import com.boa.hackathon.autodocgen.model.ClassMetadata;
import com.boa.hackathon.autodocgen.model.MethodMeta;
import com.boa.hackathon.autodocgen.model.ProjectMetadata;
import com.boa.hackathon.autodocgen.util.JsonUtil;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.file.*;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
public class DocGeneratorService {

    public File generateDocsZip(ProjectMetadata pm) throws IOException {
        Path outDir = Files.createTempDirectory("autodoc_output_");
        Path readme = outDir.resolve("README.md");
        Files.writeString(readme, buildReadme(pm));
        Path puml = outDir.resolve("diagram.puml");
        Files.writeString(puml, buildPlantUml(pm));
        Path meta = outDir.resolve("metadata.json");
        Files.writeString(meta, JsonUtil.toJson(pm));
        Path zip = outDir.resolveSibling(pm.getProjectName()+"_autodoc.zip");
        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(zip))) {
            for (Path p: List.of(readme,puml,meta)) {
                zos.putNextEntry(new ZipEntry(p.getFileName().toString()));
                Files.copy(p, zos);
                zos.closeEntry();
            }
        }
        return zip.toFile();
    }

    private String buildReadme(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(pm.getProjectName()).append("\n\n");
        sb.append("## Auto-generated Overview\n\n");
        sb.append("This documentation was automatically generated by AutoDoc.\n\n");
        sb.append("## Modules & Responsibilities\n\n");
        for(ClassMetadata c: pm.getClasses()) {
            sb.append("### ").append(c.getClassName()).append(" (").append(c.getType()).append(")\n\n");
            sb.append(c.getAiDescription()!=null? c.getAiDescription() : c.getComment()).append("\n\n");
            if (c.getMethods()!=null && !c.getMethods().isEmpty()) {
                sb.append("**Methods**:\n");
                for(MethodMeta m: c.getMethods()) {
                    sb.append("- `").append(m.getName()).append("(");
                    if (m.getParams()!=null) sb.append(String.join(", ", m.getParams()));
                    sb.append(")` : ").append(m.getAiDescription()!=null ? m.getAiDescription() : m.getComment());
                    sb.append("\n");
                }
                sb.append("\n");
            }
        }
        sb.append("## UML Diagram\n\n");
        sb.append("A PlantUML file `diagram.puml` is included. You can render it at https://plantuml.com/ or using PlantUML CLI.\n");
        return sb.toString();
    }

    private String buildPlantUml(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("skinparam classAttributeIconSize 0\n");
        for(ClassMetadata c: pm.getClasses()){
            sb.append("class ").append(ensureId(c.getClassName())).append(" {\n");
            if (c.getFields()!=null) {
                for(String f: c.getFields()) sb.append("  ").append(f.replaceAll("[\\[\\]]","")).append("\n");
            }
            sb.append("}\n");
        }
        for(ClassMetadata c: pm.getClasses()){
            if (c.getMethods()!=null) {
                for(MethodMeta m: c.getMethods()){
                    if (m.getRepositoryCalls()!=null) {
                        for(String rc: m.getRepositoryCalls()) {
                            pm.getClasses().stream()
                                    .filter(x->x.getClassName().toLowerCase().contains(rc.toLowerCase()) || x.getClassName().toLowerCase().contains("repository"))
                                    .findFirst()
                                    .ifPresent(target-> sb.append(ensureId(c.getClassName())).append(" --> ").append(ensureId(target.getClassName())).append("\n"));
                        }
                    }
                }
            }
        }
        sb.append("@enduml\n");
        return sb.toString();
    }

    private String ensureId(String s){ return s.replaceAll("[^A-Za-z0-9_]","_"); }
}
